### ISSUE TITLE
Passing a variable form controllers => EJS

### ISSUE THREAD

**Issue by aclark13861** [micahwierenga/sei-cc-7-project-2-issues#13]
I'm not able to pass a variable to EJS and Im not sure why.

TypeError: /Users/andrewscomputer/code/Mountaineer/views/trails/show.ejs:5
    3|     <section id="show-page">
    4|         <div>Trail Name: </div>
 >> 5|         <div><%= trail.name %></div>
    6|         <div>Bike Friendly: </div>
    7|         <div><%= trail.bikeFriendly ? 'Yes' : 'No' %></div>
    8|         <div>Miles: </div>

**Comment by micahwierenga** [comment]
The issue was located in the trails model. The schema definition was accidentally terminated prematurely. In other words, there were two fields that looked like they were part of the schema, but actually weren't. So, we deleted a few curly braces to fix the issue.
